version: "3.5"

services:
  mercure:
    container_name: mercure_sse_poc_sf6
    image: dunglas/mercure
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'JWT-AuctionEngine'
      MERCURE_SUBSCRIBER_JWT_KEY: 'JWT-AuctionEngine'
      MERCURE_CORS_ALLOWED_ORIGINS: '*'
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins "*"
        anonymous 1
    ports:
      - "9090:80"
      - "4433:443"


