# Read documentation at https://async-aws.com/integration/symfony-bundle.html
async_aws:
    config:
        region: eu-west-1
        accessKeyId: '%env(STORAGE_AWS_KEY)%'
        accessKeySecret: '%env(STORAGE_AWS_SECRET)%'

    clients:
        app-secrets-client:
            type: ssm

    secrets:
        enabled: true
        path: /portal/backend
        recursive: true
        client: app_secrets_client
        cache:
            pool: cache.app
            ttl: 60
