monolog:
    channels:
        - commands
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        commands:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_broadway_commands.log"
            level: info
            channels: [ "commands" ]
        nested:
            type: stream
            path: php://stderr
            level: debug
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
